# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f9597f0215c3e00bb60d68a5aa441b75a03c1511eb28b2a228f364948bc0450d643e2b25916e6678e8369afebae3139730b1cb50bb5b6001433cd8a8f2079540

test:
  secret_key_base: aeaac1b4817ec17d30508eb4e58260b679ccb1c75745902dcbd83813fe5648d45bd0119a2904238a0ef7ad73d9220de90cdd465c6a39a40ade86ed4facaa188f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
